language: node_js
node_js:
    - '10'
script:
    - npm run lint
    - npm run test
deploy:
    provider: heroku
    api_key: bxxOTDoVbScorkwfyC9k+99YiKBu604eH3pqkL3Jg1SZmHlWUD8FjSlnU5ame7gdLbyfNqaw2icYOOecO2JWEGlj+3MF6bZ8Q+t1S7sXrEKmE/xJ6/2eFNdCvCPKJzozyXjMzJmprp9FiRAel4r1iq+aBPih8Tqq8cE9a2WVDklwmf6Da2L8shUCrNxNNkX9q0BUdFfjDY+pn7nsTGsuhgSfykoda4lghdxBYOaiaiUAASwKQZtp/y2GXyMUOJ2gp0/RyS2jnuYSgq80pLVCQGP2GASw6tWu+hv7VbopbQnBVugvO2Ti8H4vl8vhppiUCfgz1I2vxBRQ53elf5fhwxNHCBb0NysVywFWZur5TSGstSGyHw1YGuTUpy/SYXaN7F+7gEiTi8y3DMBplR5dk73Bq9jrhQvjErzLEfi6R/2MF9n8iK9JGPP0SV3wmSK9FMHsk2VeaMxlnpSfiC6d7tHn9bo8gPkCoXRA6I4kj/u7NE8shCQkvxRT10DqdBUWg3senyAt7e2/cPlOvsoYoB0oJqd4pw2j7j2qgi4lVQwpMUVdDtH9i1ixlcOXzVPoFWf1Gr07CNC1c+ntclC3f/muK0XF+8fuV0rnr+lB68zQ+0YJOaUGrep7bWNfqVrtrPbuM6ojOQaxapmUTW4bOp+ZcBjViO0uT9uqivbcANc=
