version: "2"

services:
    app:
        container_name: app
        restart: always
        build: .
        command: npm run start:local
        depends_on:
            - "mongo"
        ports:
            - 3000:3000
        volumes:
            - .:/usr/app
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - 27017:27017

