version: "3"

services:
    api:
        build: .
        command: npm run start:local
        ports:
            - "3333:3333"
        environment:
            - NODE_ENV=development
            - DATABASE_URL=mongodb://mongo/coffee-order
            - PORT=3333
    mongo:
        container_name: mongo-cafe
        image: mongo:latest
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
volumes:
    mongodata:
